
class CHAT_STATUS:
  CREATE= 'CREATE'
  DISABLE= 'DISABLE'
  ACTIVE= 'ACTIVE'
  REMOVED= 'REMOVED'
  SOLVED= 'SOLVED'


class MSG_DESTINATION: 
  COMPANY= 'COMPANY'
  CLIENT= 'CLIENT'

class MSG_ROL:
  SYSTEM='SYSTEM'
  USER='USER'
  ASSISTANT='ASSISTANT'