# Generated by Django 4.2 on 2023-05-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_user_company_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user_id',
            new_name='user',
        ),
    ]
