# Generated by Django 4.2 on 2023-06-26 01:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('temperature', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='BotPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('role', models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('ASSISTANT', 'ASSISTANT')], max_length=10)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='tkbot.bot')),
            ],
        ),
    ]
