# Generated by Django 4.2 on 2023-06-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tkbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompts', models.TextField()),
                ('role', models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('ASSISTANT', 'ASSISTANT')], max_length=10)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='tkbot.bot')),
            ],
        ),
    ]
