# Generated by Django 4.2 on 2023-06-26 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatWSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CREATE', 'CREATE'), ('ACTIVE', 'ACTIVE'), ('DISABLE', 'DISABLE'), ('REMOVED', 'REMOVED'), ('SOLVED', 'SOLVED')], default='ACTIVE', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ClientWSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('client_name', models.CharField(max_length=60, null=True)),
                ('start_connection', models.DateTimeField(auto_now_add=True)),
                ('last_connection', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageWSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('creation_on', models.DateTimeField(auto_now_add=True)),
                ('destiny', models.CharField(choices=[('COMPANY', 'COMPANY'), ('CLIENT', 'CLIENT')], default='COMPANY', max_length=10)),
                ('role', models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('USER', 'USER'), ('ASSISTANT', 'ASSISTANT')], default='USER', max_length=10)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wsp.chatwsp')),
            ],
        ),
        migrations.AddField(
            model_name='chatwsp',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wsp.clientwsp'),
        ),
        migrations.AddField(
            model_name='chatwsp',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='companies.company'),
        ),
        migrations.AddField(
            model_name='chatwsp',
            name='operator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
