# Generated by Django 4.2 on 2023-06-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagewsp',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wsp.chatwsp'),
        ),
    ]
