# Generated by Django 4.2 on 2023-06-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('wsp', '0003_messagewsp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatwsp',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='companies.company'),
        ),
    ]
