# Generated by Django 4.2 on 2023-06-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsp', '0004_alter_chatwsp_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagewsp',
            name='role',
            field=models.CharField(choices=[('SYSTEM', 'SYSTEM'), ('USER', 'USER'), ('ASSISTANT', 'ASSISTANT')], default='USER', max_length=10),
        ),
    ]
